TOML config documentation: general
esl/MongooseIM pull request #2859
Opened 2020-09-04 12:08 UTC by chrzaszcz

Document the 'general' section

Functional changes either fixing bugs or simplifying the configuration.
See commit messages for more details and proposed documentation guidelines.

2020-09-07 11:47 UTC, NelsonVides reviewed
I'm honestly very happy with how this is looking 🙂 
Just a couple of language points to say, otherwise I'd approve 👍

2020-09-07 11:54 UTC, chrzaszcz commented on doc/advanced-configuration/general.md
> +* **Syntax:** TOML table, which **keys** are access groups defined in the `acl` config section and **values** specify allowed administration commands. Each value is a table with the following nested
I made a mistake here, but I know why, see https://thewritepractice.com/whose-vs-which-inanimate-objects/
However, at the moment I am not sure how to rephrase it and I will probably just follow your suggestion.

2020-09-07 19:15 UTC, NelsonVides approved these changes
I'm happy with how this looks, but I'd be good to have more reviews. Let's try to get more people to have a look, and then we'll discuss when we can get it merged :)

2020-09-08 10:29 UTC, janciesla8818 requested changes
I really like the approach and division into sections. I see that with the configuration format changed our documentation will gain as well. Really good stuff! Thanks for doing this.

I only have one comment as the `Served hostnames` in `Advanced Configuration` is left without any contents.

2020-09-08 11:31 UTC, janciesla8818 approved these changes
Looks good.

2020-09-08 11:33 UTC, merged