Fixes AMP big suite
esl/MongooseIM pull request #3778
Opened 2022-09-28 10:23 UTC by kamilwaz

Fixes AMP big suite.

2022-09-28 10:32 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/139943) / small_tests / d4fbad635a672bc7a834f6e906073f2bcf9debfa
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3778/139943/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3778/139943/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-28_10.26.40/lib.mongooseim.logs/run.2022-09-28_10.26.41/suite.log.html)

2022-09-28 11:06 UTC, mongoose-im commented
[ldap_mnesia_24](https://circleci.com/gh/esl/MongooseIM/139998) / ldap_mnesia / fc83136c56b885923a69218a55c9e06c5ac3a5e0
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3778/139998/ldap_mnesia.24.3.4)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3778/139998/ldap_mnesia.24.3.4/big/ct_run.test%40fc249f07c0b1.2022-09-28_11.01.03/index.html)
**OK: 865** / Failed: 0 / **User-skipped: 427** / Auto-skipped: 0

2022-09-29 07:58 UTC, mongoose-im commented
[ldap_mnesia_24](https://circleci.com/gh/esl/MongooseIM/140155) / ldap_mnesia / c61179eb9458161a257b65b5d2ddb055bb75a575
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3778/140155/ldap_mnesia.24.3.4)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3778/140155/ldap_mnesia.24.3.4/big/ct_run.test%405c14cee0316c.2022-09-29_07.52.22/index.html)
**OK: 865** / Failed: 0 / **User-skipped: 427** / Auto-skipped: 0

2022-09-29 08:49 UTC, NelsonVides requested changes
Brilliant! 😃

Basically the only important comment: re-enable the amp suite in `big_tests/default.spec` and `big_tests/dynamic_domains.spec`, we need to know they pass.

A second comment, a note for the future: the `c2s_preprocessing_hook` has a bit of a redundant logic, with that `drop` trick, where modern hooks as we reworked them could simply return `{stop, Acc}` and subsequent handlers won't be run so they won't have to check for the drop key. Anyway right now we want to do one refactor at a time so leave it as it is, but, we will come back here 😄

2022-09-29 08:49 UTC, NelsonVides commented on src/mod_amp.erl
> +run_initial_check(#{result := drop} = Acc, _Params, _Extra) ->
Actually this is a bug in the old code, the acc will store the result in something like `#{{hook, result} := drop}`, in `mongoose_acc` keys are pairs with a namespace. We shouldn't do that anyway, `mongoose_acc` is an abstract data structure, we should do `case mongoose_acc:get(hook, result, undefined, Acc) of` and match on `drop` or on whatever else 🤔

2022-09-29 12:15 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/140361) / small_tests / fb541ffb5b59b980600c7c985eb4c1a2c993c28c
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3778/140361/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3778/140361/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-29_12.09.40/lib.mongooseim.logs/run.2022-09-29_12.09.41/suite.log.html)

2022-09-29 12:22 UTC, chrzaszcz reviewed
I agree with Nelson's comment. The rest looks good to me :+1:

2022-10-03 14:29 UTC, mongoose-im commented
[ldap_mnesia_24](https://circleci.com/gh/esl/MongooseIM/140884) / ldap_mnesia / 57a5e59b3d0f866c74a368d127de87e77e0dfcb8
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3778/140884/ldap_mnesia.24.3.4)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3778/140884/ldap_mnesia.24.3.4/big/ct_run.test%407536852f5857.2022-10-03_14.24.11/index.html)
**OK: 1043** / Failed: 0 / **User-skipped: 427** / Auto-skipped: 0

2022-10-03 14:50 UTC, NelsonVides approved these changes
LGTM 👌🏽

2022-10-03 14:50 UTC, merged