C2s/merge master
esl/MongooseIM pull request #3816
Opened 2022-10-19 17:25 UTC by NelsonVides

2022-10-20 11:30 UTC, kamilwaz requested changes
Looks good to me.

There is only issue with compilation:

```
===> Fetching jwerl (from {git,"https://gitlab.com/vkatsuba/jwerl.git",
                 {ref,"d03607fd14a6a7556f01014af84903a3df60ff5d"}})
===> Failed to fetch and copy dep: {git,"https://gitlab.com/vkatsuba/jwerl.git",
                                  {ref,
                                      "d03607fd14a6a7556f01014af84903a3df60ff5d"}}
```

The same issue should happen on `master` as `rebar.lock` refers to the same commit. Generally, it seems that `refactoring/otp-24` refers to other commit than before.

2022-10-24 12:32 UTC, mongoose-im commented
[dynamic_domains_pgsql_mnesia_24](https://circleci.com/gh/esl/MongooseIM/146539) / pgsql_mnesia / d2193b68dd2bd7729678bb7755f2bc8eac3f85cf
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3816/146539/pgsql_mnesia.24.3.4)

2022-10-24 12:45 UTC, mongoose-im commented
[dynamic_domains_pgsql_mnesia_24](https://circleci.com/gh/esl/MongooseIM/146565) / pgsql_mnesia / b7374cce64b0cb00825dab352dbc992c19059ced
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3816/146565/pgsql_mnesia.24.3.4)

2022-10-24 13:46 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/146639) / small_tests / ff3a62a0c47d69b92ce9f2e4df0fd62f25660ed4
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3816/146639/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3816/146639/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-24_13.41.25/lib.mongooseim.logs/run.2022-10-24_13.41.26/suite.log.html)

2022-10-24 14:52 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/146663) / small_tests / 324918d83667da255fc5eb785f3295951ebe3196
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3816/146663/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3816/146663/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-24_14.47.04/lib.mongooseim.logs/run.2022-10-24_14.47.05/suite.log.html)

2022-10-24 15:06 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/146696) / small_tests / 30c9c682d518e3bc69f91aee0127cfd21075d7aa
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3816/146696/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3816/146696/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-24_15.01.18/lib.mongooseim.logs/run.2022-10-24_15.01.18/suite.log.html)

2022-10-25 14:57 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/147033) / small_tests / e30aed080c3fd4875766dc9b8ed5744e98533440
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3816/147033/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3816/147033/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-25_14.52.22/lib.mongooseim.logs/run.2022-10-25_14.52.23/suite.log.html)

2022-11-07 21:03 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/149708) / small_tests / 71e9f935f22e794511d534cadd4132026a2a0184
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3816/149708/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3816/149708/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-07_20.58.33/lib.mongooseim.logs/run.2022-11-07_20.58.34/suite.log.html)

2022-11-08 00:24 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/149733) / small_tests / 207ec0c264e648a2057833ca6c1cc6dbf4215820
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3816/149733/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3816/149733/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-08_00.18.47/lib.mongooseim.logs/run.2022-11-08_00.18.47/suite.log.html)

2022-11-09 16:23 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/150764) / small_tests / bdcd811d40ecc66fa65ad4bfea7faf64b52e4a4d
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3816/150764/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3816/150764/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-09_16.18.36/lib.mongooseim.logs/run.2022-11-09_16.18.37/suite.log.html)

2022-11-10 09:22 UTC, kamilwaz approved these changes

2022-11-10 09:22 UTC, merged