GraphQL subscriptions for stanzas
esl/MongooseIM pull request #3830
Opened 2022-10-28 09:27 UTC by chrzaszcz

WIP

2022-10-28 09:46 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/147633) / small_tests / e94c529ace61f4e3d3479f8e0afe290fe61bbda7
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3830/147633/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3830/147633/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-28_09.41.31/lib.mongooseim.logs/run.2022-10-28_09.41.32/suite.log.html)

2022-10-28 09:55 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/147658) / small_tests / 90959bd47741d672c3b7cc3a1962c6b0bfc0ae80
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3830/147658/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3830/147658/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-28_09.51.06/lib.mongooseim.logs/run.2022-10-28_09.51.07/suite.log.html)

2022-10-28 09:58 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/147684) / small_tests / 6a8e282602b8729539ca201027f63b9f335a4ac6
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3830/147684/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3830/147684/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-28_09.53.48/lib.mongooseim.logs/run.2022-10-28_09.53.48/suite.log.html)

2022-10-28 10:53 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/147761) / small_tests / 7b1d29f305c88cd886bbe391063e05e40d6b6ac1
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3830/147761/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3830/147761/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-28_10.48.25/lib.mongooseim.logs/run.2022-10-28_10.48.25/suite.log.html)

2022-10-28 12:49 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/147840) / small_tests / aa70e45d5b57169087b1bec2d48dcbe86be5dac0
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3830/147840/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3830/147840/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-28_12.45.02/lib.mongooseim.logs/run.2022-10-28_12.45.03/suite.log.html)

2022-10-28 13:07 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/147905) / small_tests / f01acdd2549a9cc79696cd85c3d39ca4cb891cb7
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3830/147905/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3830/147905/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-28_13.02.59/lib.mongooseim.logs/run.2022-10-28_13.02.59/suite.log.html)

2022-10-28 14:24 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/148049) / small_tests / 199e75e3123e24348e1c2de94435b73027ed549c
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3830/148049/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3830/148049/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-28_14.19.23/lib.mongooseim.logs/run.2022-10-28_14.19.24/suite.log.html)

2022-11-02 18:31 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/148505) / small_tests / 453435f7b6c3f3384e1c416a4cfebbd6aa976a3c
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3830/148505/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3830/148505/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-02_18.26.18/lib.mongooseim.logs/run.2022-11-02_18.26.18/suite.log.html)

2022-11-03 14:37 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/148797) / small_tests / 68c9ff2ea91a79187089c5fa6375706f56cbeb05
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3830/148797/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3830/148797/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-03_14.31.59/lib.mongooseim.logs/run.2022-11-03_14.32.00/suite.log.html)

2022-11-03 17:28 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/148828) / small_tests / 823f2a0581ac294b986cb84d533545b92668f9b2
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3830/148828/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3830/148828/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-03_17.23.16/lib.mongooseim.logs/run.2022-11-03_17.23.16/suite.log.html)

2022-11-03 18:05 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/148850) / small_tests / 19d8b2a641431284f0db567be5d5a2b87bf7713e
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3830/148850/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3830/148850/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-03_18.00.59/lib.mongooseim.logs/run.2022-11-03_18.01.00/suite.log.html)

2022-11-04 08:10 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/148877) / small_tests / 1c797063a30ab05b45c67278ea56a85ed2401f04
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3830/148877/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3830/148877/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-04_08.05.32/lib.mongooseim.logs/run.2022-11-04_08.05.32/suite.log.html)

2022-11-04 08:27 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/148905) / small_tests / 856b3798f6c1fc0206ae6886dda6adc7266ace36
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3830/148905/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3830/148905/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-04_08.22.09/lib.mongooseim.logs/run.2022-11-04_08.22.10/suite.log.html)

2022-11-04 10:54 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/149009) / small_tests / 0407461072815c305bebbc824d1cde172d2fb9ac
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3830/149009/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3830/149009/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-04_10.50.02/lib.mongooseim.logs/run.2022-11-04_10.50.03/suite.log.html)

2022-11-07 11:58 UTC, JanuszJakubiec commented on doc/graphql-api/Admin-GraphQL.md
> +**Queries** and **mutations** can be executed with the POST or GET method, as specified in the [GraphQL documenation](https://graphql.org/learn/serving-over-http/). The endpoint URL is as configured
```suggestion
**Queries** and **mutations** can be executed with the POST or GET method, as specified in the [GraphQL documentation](https://graphql.org/learn/serving-over-http/). The endpoint URL is as configured in the Listen section, e.g. `http://localhost:5551/api/graphql` for the global admin.
```

2022-11-07 11:59 UTC, JanuszJakubiec commented on doc/graphql-api/User-GraphQL.md
> +**Queries** and **mutations** can be executed with the POST or GET method, as specified in the [GraphQL documenation](https://graphql.org/learn/serving-over-http/). The endpoint URL is as configured
```suggestion
**Queries** and **mutations** can be executed with the POST or GET method, as specified in the [GraphQL documentation](https://graphql.org/learn/serving-over-http/). The endpoint URL is as configured in the Listen section, e.g. `http://localhost:5561/api/graphql`.
```

2022-11-07 12:22 UTC, JanuszJakubiec requested changes
Looks good, minor typos in docs

2022-11-08 07:54 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/149794) / small_tests / 95cfce5e9604c47bd841c69dde4e1c001d1a4a8e
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3830/149794/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3830/149794/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-08_07.49.24/lib.mongooseim.logs/run.2022-11-08_07.49.25/suite.log.html)

2022-11-08 08:36 UTC, JanuszJakubiec approved these changes

2022-11-08 08:48 UTC, merged