Refactored hook handlers in mod_auth_token
esl/MongooseIM pull request #3838
Opened 2022-11-03 10:28 UTC by pawlooss1

This PR changes all hook handlers in `mod_auth_token` module to `gen_hook` format.

2022-11-03 10:38 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/148616) / small_tests / 794afeb89a622ac6b6af3287062fc7cc4cb767cb
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3838/148616/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3838/148616/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-03_10.31.59/lib.mongooseim.logs/run.2022-11-03_10.32.00/suite.log.html)

2022-11-04 12:14 UTC, kamilwaz requested changes

2022-11-04 12:14 UTC, kamilwaz commented on src/mod_auth_token.erl
> +                         jid => Owner, acc => Acc, class => Class,
This code will produce the message like this:
```
> logger:macro_log(#{}, info, #{what => test, text => <<"test">>, reason => test, jid => J}).      
okwhen=2022-11-04T12:08:55.147132+00:00 level=info what=test reason=test pid=<0.8360.0> at=: text=test jid="{jid,<<\"test\">>,<<\"localhost\">>,<<\"mobile\">>}" 
```
I think that would be better to format JID before passing it to logger:
```suggestion
                         jid => jid:to_binary(Owner), acc => Acc, class => Class,
```
And the output:
```
> logger:macro_log(#{}, info, #{what => test, text => <<"test">>, reason => test, jid => jid:to_binary(J)}).
ok
when=2022-11-04T12:10:34.016702+00:00 level=info what=test reason=test pid=<0.8360.0> at=: text=test jid=test@localhost/mobile
```

2022-11-07 08:51 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/149111) / small_tests / c106cf6170a5428896bb4f948c564a4884511887
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3838/149111/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3838/149111/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-07_08.46.44/lib.mongooseim.logs/run.2022-11-07_08.46.45/suite.log.html)

2022-11-07 09:25 UTC, kamilwaz approved these changes

2022-11-07 11:02 UTC, NelsonVides approved these changes
👍🏽

2022-11-07 11:14 UTC, merged