Refactored hook handlers in mod_last
esl/MongooseIM pull request #3853
Opened 2022-11-10 10:18 UTC by pawlooss1

This PR changes all hook handlers in `mod_last` module to `gen_hook` format.

2022-11-10 10:26 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/151060) / small_tests / 4eb12cfc5e4e3c95efb17b0147ae102fc28be20b
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3853/151060/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3853/151060/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-10_10.21.49/lib.mongooseim.logs/run.2022-11-10_10.21.50/suite.log.html)

2022-11-10 11:41 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/151082) / small_tests / 2b15d87c9e051b8fb7075ce58afbfa2cfa03c90a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3853/151082/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3853/151082/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-10_11.36.23/lib.mongooseim.logs/run.2022-11-10_11.36.24/suite.log.html)

2022-11-10 12:58 UTC, kamilwaz requested changes
Looks good 👍 , just one small comment.

2022-11-10 12:58 UTC, kamilwaz commented on src/mod_last.erl
> +    behaviour_info/1, process_local_iq/4, process_sm_iq/4
This line can be deleted as: 
* `behaviour_info/1` don't need to be ignored,
* `process_local_iq/4` and `process_sm_iq/4` don't exist.

2022-11-10 13:15 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/151138) / small_tests / cda7dbd695477bb7344484d9ddd36f66fc3e7f49
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3853/151138/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3853/151138/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-10_13.10.20/lib.mongooseim.logs/run.2022-11-10_13.10.20/suite.log.html)

2022-11-14 14:21 UTC, kamilwaz commented on src/auth/ejabberd_auth_anonymous.erl
> +session_cleanup(Acc, #{sid := SID, jid := #jid{luser = LUser,lserver = LServer}}, _Extra) ->
```suggestion
session_cleanup(Acc, #{sid := SID, jid := #jid{luser = LUser, lserver = LServer}}, _Extra) ->
```

2022-11-21 07:47 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/153022) / small_tests / 59c7fa2d67683ee5a5f0dd05c66f8e8233193e30
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3853/153022/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3853/153022/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-21_07.42.14/lib.mongooseim.logs/run.2022-11-21_07.42.14/suite.log.html)

2022-11-21 17:06 UTC, NelsonVides approved these changes

2022-11-22 07:28 UTC, kamilwaz approved these changes

2022-11-22 07:28 UTC, merged