Use the DomainName type in GraphQL
esl/MongooseIM pull request #3856
Opened 2022-11-15 12:40 UTC by chrzaszcz

The main goal is to use the `DomainName` instead of `String` for all fields containing XMPP doman names in the GraphQL schema. This ensures that the domain is string-prepped:
- for the checks of `@use` and `@protected` directives.
- for the API logic itself. Here we might have already existing stringprepping, which we could remove as we rework the individual API modules.

Appropriate tests are added with an "unprepped" domain, that starts with a capital letter.

### Other changes
`inbox_helper` contained nested `wait_until` calls, which resulted in an almost never-ending loop of retries in case of a permanent failure. The checking logic is flattened to a single `wait_until` now.

2022-11-15 12:48 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/151918) / small_tests / 57569c10fc04913f531736650ea49fef72b77316
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3856/151918/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3856/151918/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-15_12.43.30/lib.mongooseim.logs/run.2022-11-15_12.43.31/suite.log.html)

2022-11-16 08:00 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/152110) / small_tests / b347b1796805aeb6312a93f13253eeb78d1b1d9c
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3856/152110/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3856/152110/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-16_07.55.40/lib.mongooseim.logs/run.2022-11-16_07.55.41/suite.log.html)

2022-11-16 13:48 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/152344) / small_tests / 01254081752196b9375246b8d7375f7b70acd84f
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3856/152344/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3856/152344/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-16_13.43.43/lib.mongooseim.logs/run.2022-11-16_13.43.43/suite.log.html)

2022-11-16 14:33 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/152424) / small_tests / a63484563bb292575d2fe058f2270d11d8e0f886
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3856/152424/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3856/152424/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-16_14.28.52/lib.mongooseim.logs/run.2022-11-16_14.28.52/suite.log.html)

2022-11-17 11:35 UTC, kamilwaz requested changes
Looks good, just wondering if we should also change types for the following endpoints:

- `domainsByHostType` - result type to `[DomainName]`,
- `SessionAdminQuery`,
- `domainStats`.

2022-11-17 13:01 UTC, chrzaszcz commented
> Looks good, just wondering if we should also change types for the following endpoints:
> 
>     * `domainsByHostType` - result type to `[DomainName]`,
> 
>     * `SessionAdminQuery`,
> 
>     * `domainStats`.

Will do, I apparently made a mistake when grepping for items to change.

2022-11-17 17:47 UTC, mongoose-im commented
[riak_mnesia_24](https://circleci.com/gh/esl/MongooseIM/152760) / riak_mnesia / 63bf856d6804246c2ced6e05c4716a3e5c95eddc
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3856/152760/riak_mnesia.24.3.4)

2022-11-18 07:12 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/152789) / small_tests / aa8bbb48816d2fcaefb7a1b134e09d245261f810
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3856/152789/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3856/152789/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-18_07.07.56/lib.mongooseim.logs/run.2022-11-18_07.07.57/suite.log.html)

2022-11-18 07:55 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/152814) / small_tests / b2007a7974a3138712c394749a88d7dce8f27145
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3856/152814/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3856/152814/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-18_07.50.35/lib.mongooseim.logs/run.2022-11-18_07.50.35/suite.log.html)

2022-11-18 09:28 UTC, kamilwaz approved these changes
God job :+1:

2022-11-18 09:28 UTC, merged