Improve error handling in stat
esl/MongooseIM pull request #3870
Opened 2022-11-22 11:58 UTC by kamilwaz

Improve error handling in stat

2022-11-22 12:06 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/153682) / small_tests / bc20e0cb80092fd24df3bb11abe31c24226b4677
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3870/153682/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3870/153682/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-22_12.01.25/lib.mongooseim.logs/run.2022-11-22_12.01.26/suite.log.html)

2022-11-23 10:24 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/153838) / small_tests / afb524963f480ff03d6399610c5155a36ca926e7
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3870/153838/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3870/153838/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-23_10.19.02/lib.mongooseim.logs/run.2022-11-23_10.19.03/suite.log.html)

2022-11-24 10:23 UTC, JanuszJakubiec commented on src/graphql/admin/mongoose_graphql_stats_domain.erl
> +    globalStats(<<"registeredusers">>, Domain);
```suggestion
    domainStats(<<"registeredusers">>, Domain);
```

2022-11-24 10:24 UTC, JanuszJakubiec commented on src/graphql/admin/mongoose_graphql_stats_domain.erl
> +    globalStats(<<"registeredusers">>, Domain);
I think the function name "globalStats" here is a bit misleading, because the stats called here are domain stats.

2022-11-24 10:25 UTC, JanuszJakubiec commented on src/graphql/admin/mongoose_graphql_stats_domain.erl
> +    globalStats(<<"onlineusers">>, Domain).
```suggestion
    domainStats(<<"onlineusers">>, Domain).
```

2022-11-24 10:25 UTC, JanuszJakubiec commented on src/graphql/admin/mongoose_graphql_stats_domain.erl
> +globalStats(Name, Domain) ->
```suggestion
domainStats(Name, Domain) ->
```

2022-11-24 10:26 UTC, JanuszJakubiec requested changes
I've added one minor suggestion

2022-11-24 11:05 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/154075) / small_tests / 453fc747b16ddb238d51dce6a60745ddb270ca4e
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3870/154075/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3870/154075/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-24_10.59.52/lib.mongooseim.logs/run.2022-11-24_10.59.53/suite.log.html)

2022-11-24 16:04 UTC, JanuszJakubiec approved these changes

2022-11-24 16:04 UTC, merged