Fix cassandra auth parameters parsing
esl/MongooseIM pull request #3872
Opened 2022-11-23 13:04 UTC by arcusfelis

This PR addresses:
```
12:57:11.359 [error] Supervisor {<0.559.0>,cqerl_client_sup} had child {cqerl_client,
    {{"cassandra.default.svc.cluster.local",9042},
     [{cassandra_clusters,
          [{default,
               {[{"cassandra.default.svc.cluster.local",9042}],
                [{keyspace,mongooseim},
                 {cqerl_auth_plain_handler,
                     [{<<"admin">>,<<"SECRET">>}]},
                 {tcp_opts,[{keepalive,true}]}]}}]},
      {cqerl_auth_plain_handler,[{<<"admin">>,<<"SECRET">>}]},
      {keyspace,mongooseim},
      {maps,true},
      {num_clients,5},
      {tcp_opts,[{keepalive,true}]}]},
    2} started with cqerl_client:start_link({"cassandra.default.svc.cluster.local",9042}, [{ssl,false},{keyspace,mongooseim}], #Fun<cqerl.3.76336564>, {{"cassandra.default.svc.cluster.local",9042},[{cassandra_clusters,[{default,{[{"cassandra....",...}],...}}]},...]}) at <0.573.0> exit with reason {auth_client_closed,no_credentials_provided} in context shutdown_error
```
    
Proposed changes include:
* fix

2022-11-23 13:08 UTC, mongoose-im commented
[riak_mnesia_24](https://circleci.com/gh/esl/MongooseIM/153912) / riak_mnesia / 9b1ab92682514babdd27aa6e5f5389c144aff62e
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3872/153912/riak_mnesia.24.3.4)

2022-11-28 14:59 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/154666) / small_tests / a7195e3d36f3e6ed1c79be2ecdea5e0cf51629d5
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3872/154666/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3872/154666/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-28_14.54.46/lib.mongooseim.logs/run.2022-11-28_14.54.47/suite.log.html)

2022-11-29 09:45 UTC, kamilwaz requested changes
Looks good :+1:. I would just fix the formatting.

2022-11-29 09:45 UTC, kamilwaz commented on test/config_parser_SUITE.erl
> +                  mongoose_wpool_cassandra:prepare_cqerl_opts(AuthCfg)).
```suggestion
    ?assertEqual([{auth, {cqerl_auth_plain_handler, [{<<"user">>, <<"password">>}]}},
                  {tcp_opts, [{keepalive, true}]}],
                 mongoose_wpool_cassandra:prepare_cqerl_opts(AuthCfg)).
```

2022-11-29 10:21 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/154762) / small_tests / efa2c8e9dcddb2824816d71e170f99c52afa1fe7
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3872/154762/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3872/154762/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-29_10.16.44/lib.mongooseim.logs/run.2022-11-29_10.16.45/suite.log.html)

2022-11-30 12:19 UTC, kamilwaz approved these changes

2022-11-30 12:19 UTC, merged