Reworking mongoose transport
esl/MongooseIM pull request #3982
Opened 2023-03-08 22:15 UTC by DenysGonchar

This PR addresses #

Proposed changes include:
* describe the functionality changes
* describe new or updated tests
* describe changes to the documentation

2023-03-08 22:23 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/168514) / small_tests / 9812e8890ef3d415e01b8b735b379d9544993926
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3982/168514/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3982/168514/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-03-08_22.19.29/lib.mongooseim.logs/run.2023-03-08_22.19.29/suite.log.html)

2023-03-08 23:02 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/168540) / small_tests / 6ac2c483e0fb2ef10dcab2904e1a4fbbc320fc62
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3982/168540/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3982/168540/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-03-08_22.57.42/lib.mongooseim.logs/run.2023-03-08_22.57.43/suite.log.html)

2023-03-09 00:12 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/168562) / small_tests / ba87b610ffd7218f670af1868112ef7fd265a449
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3982/168562/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3982/168562/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-03-09_00.08.02/lib.mongooseim.logs/run.2023-03-09_00.08.02/suite.log.html)

2023-03-09 01:10 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/168600) / small_tests / 758c9bce79bdacb38525499efec0122e1abe4aad
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3982/168600/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3982/168600/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-03-09_01.05.24/lib.mongooseim.logs/run.2023-03-09_01.05.25/suite.log.html)

2023-03-09 09:48 UTC, chrzaszcz approved these changes
After a quick look:
- Missing migration guide information about each changed/added/removed metric. Explain reasons for the changed metrics.
- Missing information about the websockets support for components. It should be explicit in the migration guide that options are removed, especially the options enabled by default. Motivation for the removal is necessary. It would also help the reviewer understand the reason for the removal.

2023-03-09 09:49 UTC, chrzaszcz requested changes
Github approved for me...

2023-03-09 11:00 UTC, NelsonVides reviewed
I have two minor comments, one of them is just redundant whitespace, but the other scratches a bit on the idea of the websocket rework, so probably it can be done elsewhere and not here.
Apart from that, absolutely awesome PR 😄

2023-03-10 11:52 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/169049) / small_tests / 59d982653ee34cb957e760ad7c723fb828d02370
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3982/169049/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3982/169049/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-03-10_11.48.01/lib.mongooseim.logs/run.2023-03-10_11.48.02/suite.log.html)

2023-03-10 11:56 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/169076) / small_tests / 141cf58f789759c300cd43dce7696923e0d0facb
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3982/169076/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3982/169076/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-03-10_11.51.36/lib.mongooseim.logs/run.2023-03-10_11.51.37/suite.log.html)

2023-03-10 12:02 UTC, NelsonVides reviewed
Quick doc changes, one is important, the other is only a suggestion :)

2023-03-10 12:02 UTC, NelsonVides commented on doc/migrations/6.0.0_6.1.0.md
> +Support of [listen.http.handlers.mod_websockets.service] has been removed, the component connection over WebSockets did not correspond to any XEP/RFC. Also, it was never properly described in the MIM
```suggestion
Support for [listen.http.handlers.mod_websockets.service] has been removed, the component connection over WebSockets did not correspond to any XEP/RFC, and neither it was properly described anywhere in the MIM documentation.
```
Mostly my preferred style, but no strong opinion really, just thinking out loud.

2023-03-10 12:02 UTC, DenysGonchar commented
> Oh, also, why does codecov reports so bad coverage for the newly extended `mongoose_transport` module? 🤔

taking into account that it's just patch report failed, I would say that I have changed a lot of uncovered codelines.

2023-03-10 12:06 UTC, DenysGonchar commented on src/mod_websockets.erl
>          case maybe_start_fsm(Elements, State1) of
let's make it in a context of another task. this task is about `mongoose_transport` rework and `mod_websocket` is changed only to break it's dependency with mongoose_transport.

2023-03-10 15:11 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/169138) / small_tests / 97e3c2b039418cc84f4aa5157d94a759022150de
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3982/169138/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3982/169138/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-03-10_15.06.44/lib.mongooseim.logs/run.2023-03-10_15.06.45/suite.log.html)

2023-03-14 13:57 UTC, chrzaszcz reviewed
Looks ok, nice to see the legacy modules removed.
There are some untested lines in `mongoose_transport`, but I assume they were also untested before, as most of them were moved from the legacy modules.

2023-03-14 13:57 UTC, chrzaszcz commented on src/mongoose_transport.erl
> +
Double empty line

2023-03-14 18:14 UTC, DenysGonchar commented on big_tests/tests/s2s_SUITE.erl
> +    %        [maps:get(node, RPCSpec), Type, length(AllS2SConnections), AllS2SConnections]),
I would rather leave it for now, s2s is one of the topics for the next sprint

2023-03-14 18:17 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/169613) / small_tests / 2a186b43acf6365ed26285e833bc627b71257565
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3982/169613/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3982/169613/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-03-14_18.13.45/lib.mongooseim.logs/run.2023-03-14_18.13.45/suite.log.html)

2023-03-15 02:30 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/169636) / small_tests / c75eb3ca4a443c44e10e0ab475bfaccaa7e8551a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3982/169636/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3982/169636/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-03-15_02.25.55/lib.mongooseim.logs/run.2023-03-15_02.25.55/suite.log.html)

2023-03-15 11:30 UTC, chrzaszcz approved these changes
Looks good 👍

2023-03-15 11:30 UTC, chrzaszcz commented on doc/operation-and-maintenance/MongooseIM-metrics.md
> +| `[global, data, xmpp, received, c2s, tls]` | spiral | A size (in bytes) of a data received from a client via TLS channel after decryption. |
It's still  "a data" in all these lines.

2023-03-15 11:34 UTC, merged