Update version of XEP-0045: Multi-User Chat
esl/MongooseIM pull request #4054
Opened 2023-07-04 14:34 UTC by jacekwegr

WIP

2023-07-04 14:43 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/179716) / small_tests / 1c5368a287e48b38d51abfcb2fe1e6e40e0ce7d3
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4054/179716/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4054/179716/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-07-04_14.38.28/lib.mongooseim.logs/run.2023-07-04_14.38.29/suite.log.html)

2023-07-05 14:04 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/179834) / small_tests / 743cc38dcf7bd4288597b05eada2bc193aac9cdf
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4054/179834/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4054/179834/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-07-05_13.59.35/lib.mongooseim.logs/run.2023-07-05_13.59.36/suite.log.html)

2023-07-07 14:19 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/179985) / small_tests / 48121cde934533b65910fe93d85d4796fc46d932
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4054/179985/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4054/179985/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-07-07_14.14.44/lib.mongooseim.logs/run.2023-07-07_14.14.45/suite.log.html)

2023-07-13 08:57 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/180708) / small_tests / 0bb0ec7c193cb5e3f52507a9c7200d1a9e340152
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4054/180708/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4054/180708/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-07-13_08.52.44/lib.mongooseim.logs/run.2023-07-13_08.52.45/suite.log.html)

2023-07-14 11:49 UTC, JanuszJakubiec commented on big_tests/tests/muc_SUITE.erl
> +        escalus_stanza:presence(  <<"available">>,
```suggestion
        escalus_stanza:presence(<<"available">>,
```

2023-07-14 11:49 UTC, JanuszJakubiec commented on big_tests/tests/muc_SUITE.erl
> +        escalus_stanza:presence(  <<"available">>,
```suggestion
        escalus_stanza:presence(<<"available">>,
```

2023-07-14 11:50 UTC, JanuszJakubiec commented on big_tests/tests/muc_SUITE.erl
> +                                [#xmlel{ name = <<"x">>, attrs=[{<<"xmlns">>, <<"http://jabber.org/protocol/muc">>}]}]),
```suggestion
                                [#xmlel{name = <<"x">>, attrs=[{<<"xmlns">>, <<"http://jabber.org/protocol/muc">>}]}]),
```

2023-07-14 11:50 UTC, JanuszJakubiec commented on big_tests/tests/muc_SUITE.erl
> +                                [#xmlel{ name = <<"x">>, attrs=[{<<"xmlns">>, <<"http://jabber.org/protocol/muc">>}]}]),
```suggestion
                                [#xmlel{name = <<"x">>, attrs=[{<<"xmlns">>, <<"http://jabber.org/protocol/muc">>}]}]),
```

2023-07-14 11:51 UTC, JanuszJakubiec commented on big_tests/tests/muc_SUITE.erl
> +        Namespaces = [?NS_MUC, ?NS_MUC_STABLE_ID,<<"muc_public">>, <<"muc_temporary">>,
```suggestion
        Namespaces = [?NS_MUC, ?NS_MUC_STABLE_ID, <<"muc_public">>, <<"muc_temporary">>,
```

2023-07-14 11:51 UTC, JanuszJakubiec requested changes
Looks good. I've added minor comments

2023-07-14 12:40 UTC, JanuszJakubiec commented on big_tests/tests/muc_SUITE.erl
> +                                children = [#xmlcdata{content = Msg}]},
```suggestion
                               children = [#xmlcdata{content = Msg}]},
```

2023-07-14 12:40 UTC, JanuszJakubiec commented on big_tests/tests/muc_SUITE.erl
> +                                attrs = [{<<"xmlns">>, <<"http://jabber.org/protocol/muc#user">>}]}]}.
```suggestion
                               attrs = [{<<"xmlns">>, <<"http://jabber.org/protocol/muc#user">>}]}]}.
```

2023-07-14 12:41 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/180878) / small_tests / 08cd1fc21dd1a26b220700634b1b9318c89a56c8
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4054/180878/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4054/180878/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-07-14_12.36.48/lib.mongooseim.logs/run.2023-07-14_12.36.49/suite.log.html)

2023-07-14 12:42 UTC, JanuszJakubiec commented on big_tests/tests/muc_SUITE.erl
> +                                            children=[#xmlel{name = <<"password">>, children = [#xmlcdata{content=[Password]}]} ]}]),
```suggestion
                                            children = [#xmlel{name = <<"password">>, children = [#xmlcdata{content=[Password]}]} ]}]),
```

2023-07-14 12:42 UTC, JanuszJakubiec commented on big_tests/tests/muc_SUITE.erl
> +                                [#xmlel{name = <<"x">>, attrs=[{<<"xmlns">>, <<"http://jabber.org/protocol/muc">>}]}]),
```suggestion
                                [#xmlel{name = <<"x">>, attrs = [{<<"xmlns">>, <<"http://jabber.org/protocol/muc">>}]}]),
```

2023-07-14 12:43 UTC, JanuszJakubiec requested changes
After rereading the file, I've found some more minor issues.

2023-07-14 13:04 UTC, JanuszJakubiec approved these changes
Looks good

2023-07-14 13:10 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/180906) / small_tests / 0d9d69076ada7223a511029d884b496f4dae0e76
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4054/180906/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4054/180906/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-07-14_13.06.14/lib.mongooseim.logs/run.2023-07-14_13.06.15/suite.log.html)

2023-07-14 13:54 UTC, merged