Feature/cets
esl/MongooseIM pull request #4063
Opened 2023-07-19 14:07 UTC by chrzaszcz

This PR checks if the CETS code from the feature branch passes the tests.
Ready for the final review and merge.

The following will be done after the merge:
- Add missing docs for some options, e.g. `component_backend`
- Update the migration guide with a description of `internal_databases` and the need to specify `mnesia` explicitly.

2023-07-19 14:18 UTC, mongoose-im commented
[small_tests_25_arm64](https://circleci.com/gh/esl/MongooseIM/181316) / small_tests / e84d8169910f66736e756d7701f954dac5237770
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4063/181316/small_tests.25.3-arm64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4063/181316/small_tests.25.3-arm64/small/ct_run.mongooseim@localhost.2023-07-19_14.13.53/lib.mongooseim.logs/run.2023-07-19_14.13.53/suite.log.html)

2023-07-21 11:28 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/181853) / small_tests / 5f98eeb01f6cf3ec3c911e2ec2bd22688d6df88b
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4063/181853/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4063/181853/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-07-21_11.23.40/lib.mongooseim.logs/run.2023-07-21_11.23.40/suite.log.html)

2023-08-02 08:52 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/183735) / small_tests / 34078499bd3577ad6ef970d9e1b5965a290e7a28
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4063/183735/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4063/183735/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-08-02_08.46.37/lib.mongooseim.logs/run.2023-08-02_08.46.37/suite.log.html)

2023-08-07 07:54 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/184625) / small_tests / a3647acc646551c4c7667b10fdf9e435da8198cc
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4063/184625/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4063/184625/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-08-07_07.48.51/lib.mongooseim.logs/run.2023-08-07_07.48.52/suite.log.html)

2023-08-07 08:08 UTC, mongoose-im commented
[elasticsearch_and_cassandra_25](https://circleci.com/gh/esl/MongooseIM/184670) / elasticsearch_and_cassandra_mnesia / e2369988350da9a0333ae10242dc0e5ffa6d076d
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4063/184670/elasticsearch_and_cassandra_mnesia.25.3-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4063/184670/elasticsearch_and_cassandra_mnesia.25.3-amd64/big/ct_run.test%40c2a000b5e63a.2023-08-07_08.04.54/index.html)
**OK: 369** / Failed: 0 / **User-skipped: 38** / Auto-skipped: 0

2023-08-07 09:41 UTC, mongoose-im commented
[elasticsearch_and_cassandra_25](https://circleci.com/gh/esl/MongooseIM/184772) / elasticsearch_and_cassandra_mnesia / 411c00708fad9f653beb7317e53d9338f37f5748
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4063/184772/elasticsearch_and_cassandra_mnesia.25.3-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4063/184772/elasticsearch_and_cassandra_mnesia.25.3-amd64/big/ct_run.test%40f7aeee6844af.2023-08-07_09.38.55/index.html)
**OK: 369** / Failed: 0 / **User-skipped: 38** / Auto-skipped: 0

2023-08-08 07:17 UTC, mongoose-im commented
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/185285) / small_tests / 48b9569ee827cd859e7282ef7875ec0ef2bf0bd0
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4063/185285/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4063/185285/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-08-08_07.12.42/lib.mongooseim.logs/run.2023-08-08_07.12.42/suite.log.html)

2023-08-08 12:13 UTC, NelsonVides requested changes
Ok, with such a gigantic diff, I'm not going to carefully read and verify everything changed here, some sections I'll only skim over, trusting that previous rounds of review and tests went well.
Notes:
- I've checked documentation, seems good to me. Not extensive enough but what is there is fine.
- I'm not verifying that everything mnesia now has a cets alternative, I trust having disabled mnesia in tests checked that already.
- I'm not paying thorough attention to pieces like bosh, jingle, or regular muc, I've only read the main module and it seems good, I trust their respective backends and/or helper modules are cool. Though btw, if we already created a dir for `muc` with the `_online_` helpers, we might have as well put `mod_muc` in there. Not important, just mentioning.
- Changes to ejabberd_router, components, and s2s, they're amazing, thank you!

-----
Some comments request small changes, specially the one in `ejabberd_app:start/2`, please fix that one 🙏🏽

2023-08-08 14:01 UTC, arcusfelis commented on src/mongoose_node_num.erl
> +-include("mongoose_logger.hrl").
sssh, don't be Hank xd

2023-08-08 14:06 UTC, arcusfelis commented on rebar.config
> +  {cets, {git, "https://github.com/esl/cets.git", {branch, "main"}}},
Yes, we will do before release (or you could try to make a package, hope the name is free... or we would have to use short eslcets)

2023-08-08 14:14 UTC, NelsonVides commented on src/ejabberd_app.erl
> +    db_init(),
This one I'll insist is strictly required, please fix.

2023-08-08 14:14 UTC, arcusfelis commented on src/ejabberd_sup.erl
> +          permanent, infinity, worker, [pg]},
rewrite it all, there is a lot of repetition in this module...

2023-08-08 14:34 UTC, NelsonVides approved these changes
LGTM 🔥🔥🔥

2023-08-08 14:37 UTC, mongoose-im commented
[elasticsearch_and_cassandra_25](https://circleci.com/gh/esl/MongooseIM/185737) / elasticsearch_and_cassandra_mnesia / c5faa49326f12ab22e3444f857b9b8a126194a2e
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4063/185737/elasticsearch_and_cassandra_mnesia.25.3-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4063/185737/elasticsearch_and_cassandra_mnesia.25.3-amd64/big/ct_run.test%4001180d2f997e.2023-08-08_14.34.20/index.html)
**OK: 369** / Failed: 0 / **User-skipped: 38** / Auto-skipped: 0

2023-08-08 14:57 UTC, merged